---
- name: Find enabled sites
  find:
    paths: {{nginx_conf_dir}}/sites-enabled
  register: enabled_sites

- name: Disable unmanaged sites
  file:
    path: "{{nginx_conf_dir}}/sites-enabled/{{ item.path | basename }}"
    state: absent
  with_items: "{{ enabled_sites.files | default([]) }}"
  # 'item.conf' => 'item'
  when: item.path | basename not in nginx_sites.keys()
  notify:
    - reload nginx

- name: Find config files
  find:
    path: {{nginx_conf_dir}}/conf.d
    patterns: *.conf
    file_type: file
     -maxdepth 1 -exec basename {} \;
  register: config_files
  changed_when: False

- name: Remove unmanaged config files
  file:
    name: "{{nginx_conf_dir}}/conf.d/{{ item.path | basename }}"
    state: absent
  with_items: "{{ config_files.files | default([]) }}"
  # 'item.conf' => 'item'
  when: item.path | basename | splitext  not in nginx_configs.keys()
  notify:
    - reload nginx
